---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
##Submitted by maander6, `r date()`
Data  (activity.csv) for this analysis is provided by the Reproducible Research 
Coursera Course Instructors.  It is placed in the working directory for the 
analysis.

## Loading and preprocessing the data

Libraries dplyr and ggplot2 are required for the analysis

```{R}
  library(dplyr)
  library(ggplot2)
```

Data is loaded using the read.csv() function, and then converted to a table.
The type of data in each column is converted to date format (date column) or 
numeric format (steps column) to allow for subsequent processing

```{R Loading_Data}
# Read the data and convert to a data table.  Once converted, change the date
# column to date format, and the steps column to numeric format

  temp <- read.csv("activity.csv")
  data <- tbl_df(temp)
  data$date <- as.Date(data$date, "%Y-%m-%d")
  data$steps <- as.numeric(data$steps)
```


## What is mean total number of steps taken per day?

Subset the data by selecting only those rows that do not have NA for
the number of steps in the interval.  Once the data has been subsetted,
group the data by date and calculate the total number of steps, the average
number of steps, and the median number of steps for each date.

```{R Mean_Steps_per_Day}
  df <- subset(data, !is.na(data$steps))
  avg.step <- df %>% group_by(date) %>% summarize(total=sum(steps))
  avg <- mean(avg.step$total)
  mdn <- median(avg.step$total)
```

The mean number of steps taken is `r format(avg, nsmall=2)` and the median number of steps each 
day is `r format(mdn, digits=2)`

A Histogram is created to display the distribution of total steps taken on any given
day from October and November of 2012.  The data is binned in groups of 
1000 steps, and the histogram has the mean of the daily steps superimposed with the 
vertical black line.

```{R Histogram_Steps}
  qplot(avg.step$total, binwidth=1000, fill="red") + 
          geom_vline(xintercept=avg, color="black") +
          xlab("Number of Steps") +
          ylab("Frequency")
```

## What is the average daily activity pattern?
Grouping the activity data by the interval allows the analysis to evaluate the
average activity pattern throughout the day.  This pattern for October and 
November is shown in the following line graph.

```{R Daily_Activity_Pattern}
  avg.interval <- df %>% group_by(interval) %>% summarize(avg = mean(steps),
     stdev = sd(steps))
  qplot(avg.interval$interval, avg.interval$avg, data=avg.interval, geom="line") +
    xlab("Daily Interval, minutes") +
    ylab("Average Steps")
```

From this data, the interval with the highest daily activity can be determined.

```{R Highest_Activity_Interval}
   maxint <- avg.interval$interval[which(avg.interval$avg == max(avg.interval$avg))]
   maxint
```
The interval with the highest average activity (measured in steps) is at
`r maxint` minutes.

## Imputing missing values
In this section the the number of missing values in the activity data set is
calculated and the missing values are replaced.  The missing values are replaced
by generating a random number from a normal distribution calculated using the
mean and standard deviation of the number of steps for that interval (calculated 
previously).  If the random number generated by the normal distribution is
negative, a value of 0 steps is recorded for that interval.

```{R Missing_Data}
# Calculate the number of missing rows of data
  df.missing <- subset(data, is.na(data$steps))
  missing <- nrow(df.missing)
```

There are `r missing` missing values in the activity data set.

```{R Impute_new_data}
# impute function takes 2 data tables, one (df) is a data table that has all the 
# missing step values (NA), and the other (df1) is a data table that contains
# the statistics for the activity for each 5-minute interval during any day.
  impute <- function(df, df1){
    num <- nrow(df1)
# seed the random number generator so that the same random values are
# calculated for each normal distribution
    set.seed(1)
    for (i in 1:num){
      val <- round(rnorm(1, df1$avg[i], df1$stdev[i]))
      if (val < 0){
        val <- 0
      } 
    df$steps[which(df$interval == df1$interval[i])] <- val
  }
  df
}
  
  df.replaced <- impute(df.missing, avg.interval)
  data1 <- arrange(rbind(df, df.replaced), date, interval)
  data1
  
  avg.step.cor <- data1 %>% group_by(date) %>% summarize(total=sum(steps))
  avg1 <- mean(avg.step.cor$total)
  mdn1 <- median(avg.step.cor$total)
```

After imputing the data set to add values where NA had previously been reported,
it is found that the mean daily activity is `r format(avg1, nsmall=2)`, and the median 
daily activity is `r format(mdn1, digits=2)`.  Not unexpectedly, since we added steps to
to the activity data set, the average daily activity increased by `r format((avg1-avg), nsmall=2)`,
and the median daily activity increased by `r format((mdn1-mdn), digits=2)`.

```{R Imputed_data_histogram}
  qplot(avg.step.cor$total, binwidth=1000) + 
          geom_vline(xintercept=avg1, color="green") +
          geom_vline(xintercept=mdn1, color="red") +
          xlab("Number of Steps") +
          ylab("Frequency")
  
```

A histogram is created using the imputed data.  Vertical lines are superimposed
on the histogram to show the mean number of steps for the imputed
distribution (green) and the median number of steps for the imputed
distribution (red).


## Are there differences in activity patterns between weekdays and weekends?
Using the weekday() function, the day of the week can be added to the activity data.

```{R Day_of_week}
  dayofweek <- weekdays(data1$date)
  data1 <- cbind(data1, dayofweek)
```

Using this data, we can subset the activity data based on weekday or weekend.
This allows one to compare the daily activity at 5-minute intervals to see if
there are differences in the activity pattern for weekdays and weekend days.

```{R Weekday_Weekend_comparison}
## subset the data by day of week, then add a column identifying weekend 
## or weekday
  weekday <- subset(data1, data1$dayofweek != c("Saturday", "Sunday"))
  weekday <- mutate(weekday, DorE="weekday")
  weekend <- subset(data1, data1$dayofweek == c("Saturday", "Sunday"))
  weekend <- mutate(weekend, DorE="weekend")
## recombine the weekend and weekday data into a single table, and group the
## data by weekend/weekday then by interval
  data2 <- arrange(rbind(weekday, weekend), date, interval)
  data2 <- data2 %>% group_by(DorE, interval) %>% summarize(avg=mean(steps))
```

```{R Line_plot_comparison}
## plot the data with 2 facets corresponding to the activity for (1)
## weekdays, and (2) weekends
  ggplot(data2, aes(x=interval, y=avg)) + 
        geom_line() + 
        facet_grid(DorE ~ .) +
        xlab("Interval, minutes") +
        ylab("Average Number of Steps")
```

Clearly there is a difference in the activity pattern depending on whether the
data corresponds to a weekday, or to a weekend

